version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing Maven...
      - yum install -y maven
  pre_build:
    commands:
      - echo Cleaning project...
      - mvn clean
  build:
    commands:
      - echo Building project with Maven...
      - mvn package
  post_build:
    commands:
      - echo Build completed successfully.
      - ls -l target/

artifacts:
  files:
    - target/husni-web-project.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no
